/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_Utils_Objects_appManager_consoleMode_ConsoleMode */

#ifndef _Included_base_Utils_Objects_appManager_consoleMode_ConsoleMode
#define _Included_base_Utils_Objects_appManager_consoleMode_ConsoleMode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_Utils_Objects_appManager_consoleMode_ConsoleMode
 * Method:    setConsoleMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_base_1Utils_1Objects_appManager_consoleMode_ConsoleMode_setConsoleMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     base_Utils_Objects_appManager_consoleMode_ConsoleMode
 * Method:    getConsoleMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_base_1Utils_1Objects_appManager_consoleMode_ConsoleMode_getConsoleMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
